[workspace]
members = ["gfx", "maze"]

[package]
name = "twisty"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.1.1", features = ["derive"] }
rand = "0.8.5"
twisty-gfx = { path = "./gfx" }
twisty-maze = { path = "./maze" }
