[package]
name = "twisty-gfx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
sdl2 = { version = "0.35.2", features = ["gfx", "image", "ttf"] }
twisty-maze = { path = "../maze" }
